version: "3.3"
services:
  auth-api:
    build: ./auth-api
    depends_on:
      - database
    ports:
      - '8080:8080'

  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password