version: "3.3"
services:
  auth-api:
    build: ./auth-api
    depends_on:
      - database
    ports:
      - '8080:8080'

  player-api:
    build: ./player-api
    depends_on:
      - database
    ports:
      - '8081:8081'

  monster-api:
    build: ./monster-api
    depends_on:
      - database
    ports:
      - '8082:8082'

  invocation-api:
    build: ./Invocation-api
    depends_on:
      - database
    ports:
      - '8083:8083'

  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password